### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by mwhamgenomics**
- PEP8 refactor
- Using Parameter subclasses to stop the `warnings.warn` messages from NoneType parameters
- Caching taxids in contamination_checks.Blast

### CODE REVIEW

**Review by tcezard — APPROVED** [review]
This looks fine. Did you run an integration test on it ?

**Review by katieemelianova — APPROVED** [review]

**Comment by mwhamgenomics** [comment]
Integration tests ran successfully on the latest version of this branch.

**Comment by tcezard** [comment]
This can be merged then

**Comment by tcezard** [comment]
Unless there are more things to add this refactor can be merged.

**Pull request merged**
